services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: requirements/mariadb
    networks: 
      - inception
    volumes:
      - dbdata:/var/lib/mysql/
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception
    volumes:
      - wpdata:/var/www/html/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wpdata:/var/www/html/wordpress
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception:
    driver: bridge

volumes:
  wpdata:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress
  dbdata:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
